language: python
python:
  - '3.8'

branches:
  only:
    - staging

before_script:
  - pip install pipenv
  - pipenv install
  - pipenv shell

env: DJANGO_SETTINGS_MODULE="purbeurre.settings.travis"

services:
  - postgresql

script:
  - ./manage.py test